name: CI

on: [push, pull_request, check_run]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Prepare environment
        run: |
          python -m pip install --upgrade pip
          python setup.py install
      - name: install pytest
        run: |
          pip install pytest
      - name: execute test.py on toy example
        run: |
          cd tests
          py.test test.py
